Submitting response
code-mancers/g-bot pull request #24
Opened 2022-09-08 09:10 UTC by ayushdevelop

# Related Issue

- https://github.com/code-mancers/g-bot/issues/4

# Functionalities Added or Changed

- On clicking the `Submit` button visible on the modal the response will be populated in the channel set for exampe `gather-bot`
- The response will be submitted as user

# Checklist

- [x] Uploaded screenshots

# Screenshots
![Response of Standup](https://user-images.githubusercontent.com/87638385/189083224-1f392e6c-f29b-4f47-bfa7-125b6cdf688d.png)

2022-09-10 05:50 UTC, SujayPrabhu96 requested changes

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/constants/standupQuestions.ts
> +  { question: 'How do you feel today?', id: 'question_one' },
When prettier configuration is to use double quotes why this change included ?

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/actions/notWorking.ts
> +type NotWorkingArguments = {
Not working feature is added in next PR right ? Why it is in this PR ?

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +  client: {
As the arguments type remains same for actions, views, we can define the type in `src/types` and import it wherever required

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +}: StandupModalArguments) => {
Optional: As in frontend we usually name it `ComponentProps`
```suggestion
}: StandupModalArgs) => {
```

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +
remove empty line

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +
same

2022-09-10 05:50 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +
same^

2022-09-12 08:10 UTC, SujayPrabhu96 commented on server/src/listeners/views/modalView.ts
> +      channel: "C0403497QV8",
Even though this hard-coding is for temporary, I would suggest to put it in env

2022-09-12 08:12 UTC, ayushdevelop commented on server/src/listeners/views/modalView.ts
> +      channel: "C0403497QV8",
okay doing it

2022-09-12 08:35 UTC, SujayPrabhu96 approved these changes

2022-09-12 08:35 UTC, merged