Integrating channel api
code-mancers/g-bot pull request #74
Opened 2022-10-06 15:52 UTC by ayushdevelop

# Related Issue

- https://github.com/code-mancers/g-bot/issues/22

# functionalities Added or Changed

- integrated the api for fetching channels with frontend

2022-10-11 13:56 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +  console.log(channelList);
remove

2022-10-11 13:56 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +
remove empty line

2022-10-11 14:00 UTC, SujayPrabhu96 requested changes

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/src/apis/fetchChannels.ts
> +
remove empty line

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/src/apis/fetchChannels.ts
> +  return response;
```suggestion
  return response.data;
```

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +
remove empty line

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +        <Dropdown list={channelList} />
As we are not writing test cases, do we need a component ? can we do
```suggestion
        <SelectInput choices={channelList} />
```

2022-10-11 14:00 UTC, SujayPrabhu96 commented on server/src/services/__mock__/channel.mock.ts
> +const mockChannelData = [
remove mock file

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/.env
> +REACT_APP_PUBLIC_URL = http://localhost:8000
`.env` should not be pushed to repo. Rename it to `.env.example`

2022-10-11 14:00 UTC, SujayPrabhu96 commented on client/jest.config.js
> +module.exports = {
remove this file

2022-10-11 14:02 UTC, SujayPrabhu96 requested changes

2022-10-11 14:02 UTC, SujayPrabhu96 commented on client/src/apis/fetchChannels.ts
> +import instance from ".";
rename the file to `channels.ts`

2022-10-11 14:02 UTC, SujayPrabhu96 commented on client/src/apis/fetchChannels.ts
> +  const response = await instance.get("/channels");
Lets update our endpoint to `/api/v1/channels`. Please do the necessary changes in backend as well

2022-10-11 16:53 UTC, ayushdevelop commented on client/.env
> +REACT_APP_PUBLIC_URL = http://localhost:8000
sorry sorry I did add it to .gitIgnore I think I forgot saving. Will fix it

2022-10-12 04:13 UTC, SujayPrabhu96 requested changes

2022-10-12 04:13 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +        const data = await fetchChannels();
```suggestion
        const { data: channels } = await fetchChannels();
```

2022-10-12 04:28 UTC, SujayPrabhu96 approved these changes

2022-10-12 04:28 UTC, merged