Integrating channel members api
code-mancers/g-bot pull request #90
Opened 2022-10-12 07:50 UTC by ayushdevelop

# Related Issue

- https://github.com/code-mancers/g-bot/issues/23

# functionalities Added or Changed

- Integrated the api for fetching channel members of the channel we select.
- Api interacts with the backend that returns the channel members using `slack-api`
- Used `react-loading` for adding loading animation while members are fetched on selecting the channel

# Additional Info

- Installed the package `react-loading` for adding loading animations

2022-10-12 09:12 UTC, SujayPrabhu96 requested changes

2022-10-12 09:12 UTC, SujayPrabhu96 commented on client/src/apis/channelMembers.ts
> +const fetchChannelMembers = async (channelValue: string) => {
```suggestion
const fetchChannelMembers = async (channelId: string) => {
```

2022-10-12 09:12 UTC, SujayPrabhu96 commented on client/src/apis/channelMembers.ts
> +  const response = await instance.get(`/channels/${channelValue}/members`);
```suggestion
  const response = await instance.get(`/channels/${channelId}/members`);
```

2022-10-12 09:12 UTC, SujayPrabhu96 commented on client/src/apis/channels.ts
> +const fetchChannels = async () => {
Lets do named export for all api methods. Because other api files will have multiple methods in single file. So, we can maintain consistency by doing named export for all methods
```suggestion
export const fetchChannels = async () => {
```

2022-10-12 09:12 UTC, SujayPrabhu96 commented on client/src/components/Standups/StandupCreate.tsx
> +  RaRecord,
What's this ? 😄

2022-10-13 04:09 UTC, SujayPrabhu96 approved these changes

2022-10-13 04:10 UTC, merged

2022-10-13 04:17 UTC, ayushdevelop commented on client/src/components/Standups/StandupCreate.tsx
> +  RaRecord,
It is a type from `react-admin` had to assign to `events` argument in `handleChange` otherwise was throwing errors